//! Database migration system

use chrono::Utc;
use sqlx::Row;
use std::fs;
use std::path::{Path, PathBuf};
use thiserror::Error;

/// A specialized `Result` type wrapping [`MigrationError`]
pub type MigrationResult<T> = std::result::Result<T, MigrationError>;

/// Errors that can occur during migration operations
#[derive(Debug, Error)]
pub enum MigrationError {
    #[error(transparent)]
    Io(#[from] std::io::Error),
    #[error(transparent)]
    Database(#[from] sqlx::Error),
    #[error("invalid migration filename `{filename}`")]
    InvalidFilename { filename: String },
}

/// Migration file
#[derive(Debug)]
pub struct Migration {
    pub version: String,
    pub name: String,
    pub up_sql: String,
    pub down_sql: String,
}

impl Migration {
    /// Create a new migration with a timestamp-based version
    pub fn new(name: &str) -> Self {
        let timestamp = Utc::now().format("%Y%m%d%H%M%S").to_string();
        let version = format!("{}_{}", timestamp, name);

        Self {
            version,
            name: name.to_string(),
            up_sql: String::new(),
            down_sql: String::new(),
        }
    }

    /// Load a migration from a `.sql` file, converting non-IO errors to `io::Error`
    pub fn from_file(path: impl AsRef<Path>) -> Result<Self, std::io::Error> {
        Self::from_file_checked(path).map_err(|err| match err {
            MigrationError::Io(io) => io,
            other => std::io::Error::new(std::io::ErrorKind::InvalidData, other.to_string()),
        })
    }

    /// Load a migration from a `.sql` file, returning a [`MigrationError`] on failure
    pub fn from_file_checked(path: impl AsRef<Path>) -> MigrationResult<Self> {
        let path = path.as_ref();
        let content = fs::read_to_string(path)?;

        let filename = path.file_stem().and_then(|s| s.to_str()).ok_or_else(|| {
            MigrationError::InvalidFilename {
                filename: path.display().to_string(),
            }
        })?;

        // Parse filename: 20240101120000_create_users
        let parts: Vec<&str> = filename.splitn(2, '_').collect();
        if parts.len() != 2 {
            return Err(MigrationError::InvalidFilename {
                filename: filename.to_string(),
            });
        }

        let version = filename.to_string();
        let name = parts[1].to_string();

        // Split content into up/down SQL
        let sections: Vec<&str> = content.split("-- migrate:down").collect();
        let up_sql = sections
            .get(0)
            .unwrap_or(&"")
            .replace("-- migrate:up", "")
            .trim()
            .to_string();
        let down_sql = sections.get(1).unwrap_or(&"").trim().to_string();

        Ok(Self {
            version,
            name,
            up_sql,
            down_sql,
        })
    }

    /// Write the migration SQL file to the given directory
    pub fn save(&self, migrations_dir: impl AsRef<Path>) -> Result<PathBuf, std::io::Error> {
        let migrations_dir = migrations_dir.as_ref();
        fs::create_dir_all(migrations_dir)?;

        let filename = format!("{}.sql", self.version);
        let path = migrations_dir.join(filename);

        let content = format!(
            "-- Generated by `toxi generate migration {name}`.\n-- Write the forward change below. Keep each SQL statement terminated with a semicolon.\n-- migrate:up\n{up}\n\n-- Write the rollback that undoes the change below.\n-- If a rollback is unsafe, explain it here before the SQL.\n-- migrate:down\n{down}\n",
            name = self.name,
            up = self.up_sql,
            down = self.down_sql
        );

        fs::write(&path, content)?;
        Ok(path)
    }
}

/// Migration manager
pub struct MigrationManager {
    migrations_dir: PathBuf,
}

impl MigrationManager {
    /// Create a new `MigrationManager` for the given migrations directory
    pub fn new(migrations_dir: impl AsRef<Path>) -> Self {
        Self {
            migrations_dir: migrations_dir.as_ref().to_path_buf(),
        }
    }

    /// List all migration files in the migrations directory, sorted by version
    pub fn list_migrations(&self) -> Result<Vec<Migration>, std::io::Error> {
        self.list_migrations_checked().map_err(|err| match err {
            MigrationError::Io(io) => io,
            other => std::io::Error::new(std::io::ErrorKind::InvalidData, other.to_string()),
        })
    }

    /// List all migration files, returning a [`MigrationResult`]
    pub fn list_migrations_checked(&self) -> MigrationResult<Vec<Migration>> {
        let mut migrations = Vec::new();

        if !self.migrations_dir.exists() {
            return Ok(migrations);
        }

        for entry in fs::read_dir(&self.migrations_dir)? {
            let entry = entry?;
            let path = entry.path();

            if path.is_file() && path.extension().and_then(|s| s.to_str()) == Some("sql") {
                let migration = Migration::from_file_checked(&path)?;
                migrations.push(migration);
            }
        }

        // Sort by version
        migrations.sort_by(|a, b| a.version.cmp(&b.version));

        Ok(migrations)
    }

    /// Create a new migration file with the given name, returning the file path
    pub fn create_migration(&self, name: &str) -> Result<PathBuf, std::io::Error> {
        self.create_migration_checked(name)
            .map_err(|err| match err {
                MigrationError::Io(io) => io,
                other => std::io::Error::new(std::io::ErrorKind::InvalidData, other.to_string()),
            })
    }

    /// Create a new migration file, returning a [`MigrationResult`]
    pub fn create_migration_checked(&self, name: &str) -> MigrationResult<PathBuf> {
        let migration = Migration::new(name);
        Ok(migration.save(&self.migrations_dir)?)
    }

    /// Ensure migrations table exists
    pub async fn ensure_migrations_table(&self, db: &impl crate::Database) -> crate::Result<()> {
        let sql = match db.db_type() {
            crate::DatabaseType::Sqlite => {
                r#"
                CREATE TABLE IF NOT EXISTS _migrations (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    version TEXT NOT NULL UNIQUE,
                    applied_at INTEGER NOT NULL
                )
                "#
            }
            crate::DatabaseType::Postgres => {
                r#"
                CREATE TABLE IF NOT EXISTS _migrations (
                    id BIGSERIAL PRIMARY KEY,
                    version TEXT NOT NULL UNIQUE,
                    applied_at BIGINT NOT NULL
                )
                "#
            }
            crate::DatabaseType::MySql => {
                r#"
                CREATE TABLE IF NOT EXISTS _migrations (
                    id BIGINT AUTO_INCREMENT PRIMARY KEY,
                    version VARCHAR(255) NOT NULL UNIQUE,
                    applied_at BIGINT NOT NULL
                )
                "#
            }
        };
        db.execute(sql).await?;
        Ok(())
    }

    /// Get list of applied migrations
    pub async fn get_applied_migrations(
        &self,
        db: &impl crate::Database,
    ) -> crate::Result<Vec<String>> {
        self.ensure_migrations_table(db).await?;

        let rows = db
            .query("SELECT version FROM _migrations ORDER BY version")
            .await?;
        let mut versions = Vec::new();

        for row in rows {
            if let Ok(version) = row.try_get::<String, _>("version") {
                versions.push(version);
            }
        }

        Ok(versions)
    }

    /// Mark migration as applied
    pub async fn mark_migration_applied(
        &self,
        db: &impl crate::Database,
        version: &str,
    ) -> crate::Result<()> {
        self.ensure_migrations_table(db).await?;

        let timestamp = chrono::Utc::now().timestamp();
        
        // Use database-specific placeholder syntax
        let query_sql = match db.db_type() {
            crate::DatabaseType::Postgres => "INSERT INTO _migrations (version, applied_at) VALUES ($1, $2)",
            crate::DatabaseType::MySql => "INSERT INTO _migrations (version, applied_at) VALUES (?, ?)",
            crate::DatabaseType::Sqlite => "INSERT INTO _migrations (version, applied_at) VALUES (?, ?)",
        };
        
        let query = sqlx::query(query_sql)
            .bind(version)
            .bind(timestamp);
        db.execute_query(query).await
            .map(|_| ())
            .map_err(|e| {
                eprintln!("[WARN] Migration tracking failed for '{}': {}", version, e);
                e
            })
    }

    /// Remove migration record (for rollback)
    pub async fn mark_migration_reverted(
        &self,
        db: &impl crate::Database,
        version: &str,
    ) -> crate::Result<()> {
        // Use database-specific placeholder syntax
        let query_sql = match db.db_type() {
            crate::DatabaseType::Postgres => "DELETE FROM _migrations WHERE version = $1",
            crate::DatabaseType::MySql => "DELETE FROM _migrations WHERE version = ?",
            crate::DatabaseType::Sqlite => "DELETE FROM _migrations WHERE version = ?",
        };
        
        let query = sqlx::query(query_sql).bind(version);
        db.execute_query(query).await
            .map(|_| ())
            .map_err(|e| {
                eprintln!("[WARN] Migration revert failed for '{}': {}", version, e);
                e
            })
    }

    /// Get pending migrations
    pub async fn get_pending_migrations(
        &self,
        db: &impl crate::Database,
    ) -> Result<Vec<Migration>, Box<dyn std::error::Error>> {
        Ok(self.get_pending_migrations_checked(db).await?)
    }

    pub async fn get_pending_migrations_checked(
        &self,
        db: &impl crate::Database,
    ) -> MigrationResult<Vec<Migration>> {
        let all_migrations = self.list_migrations_checked()?;
        let applied = self.get_applied_migrations(db).await?;

        let pending: Vec<Migration> = all_migrations
            .into_iter()
            .filter(|m| !applied.contains(&m.version))
            .collect();

        Ok(pending)
    }

    /// Apply all pending migrations.
    /// Each migration's SQL is executed directly, then recorded in the tracking table.
    /// Note: For transactional execution, use `DbPool::with_transaction()` manually.
    pub async fn apply_pending_migrations(
        &self,
        db: &impl crate::Database,
    ) -> Result<Vec<String>, Box<dyn std::error::Error>> {
        self.apply_pending_migrations_checked(db).await
            .map_err(|e| Box::new(e) as Box<dyn std::error::Error>)
    }

    pub async fn apply_pending_migrations_checked(
        &self,
        db: &impl crate::Database,
    ) -> crate::OrmResult<Vec<String>> {
        let pending = self.get_pending_migrations_checked(db).await
            .map_err(|e| crate::OrmError::Database(sqlx::Error::Protocol(e.to_string().into())))?;
        let mut applied_versions = Vec::new();

        for migration in &pending {
            // Execute up SQL
            if !migration.up_sql.is_empty() {
                // Split into individual statements
                for stmt in migration.up_sql.split(';') {
                    let stmt = stmt.trim();
                    if stmt.is_empty() {
                        continue;
                    }
                    db.execute(stmt).await?;
                }
            }

            // Mark as applied
            self.mark_migration_applied(db, &migration.version).await?;
            applied_versions.push(migration.version.clone());
        }

        Ok(applied_versions)
    }

    /// Rollback the last N applied migrations
    pub async fn rollback_migrations(
        &self,
        db: &impl crate::Database,
        steps: usize,
    ) -> Result<Vec<String>, Box<dyn std::error::Error>> {
        self.rollback_migrations_checked(db, steps).await
            .map_err(|e| Box::new(e) as Box<dyn std::error::Error>)
    }

    pub async fn rollback_migrations_checked(
        &self,
        db: &impl crate::Database,
        steps: usize,
    ) -> crate::OrmResult<Vec<String>> {
        if steps == 0 {
            return Ok(Vec::new());
        }

        let applied = self.get_applied_migrations(db).await?;
        if applied.is_empty() {
            return Ok(Vec::new());
        }

        // Get the last N applied versions (in reverse order)
        let to_rollback: Vec<String> = applied
            .iter()
            .rev()
            .take(steps)
            .cloned()
            .collect();

        let mut reverted_versions = Vec::new();

        for version in &to_rollback {
            // Find the corresponding migration file
            let all_migrations = self.list_migrations_checked().map_err(|e| {
                crate::OrmError::Database(sqlx::Error::Protocol(e.to_string().into()))
            })?;
            let migration = all_migrations
                .iter()
                .find(|m| m.version == *version)
                .ok_or_else(|| crate::OrmError::NotFound {
                    model: "migration",
                    id: version.clone(),
                })?;

            if migration.down_sql.is_empty() {
                return Err(crate::OrmError::Validation(format!(
                    "migration {} has no down SQL, cannot rollback",
                    version
                )));
            }

            // Execute down SQL
            for stmt in migration.down_sql.split(';') {
                let stmt = stmt.trim();
                if stmt.is_empty() {
                    continue;
                }
                db.execute(stmt).await?;
            }

            // Remove from tracking
            self.mark_migration_reverted(db, &migration.version).await?;
            reverted_versions.push(version.clone());
        }

        Ok(reverted_versions)
    }

    /// Apply a single migration by version
    pub async fn apply_migration(
        &self,
        db: &impl crate::Database,
        version: &str,
    ) -> MigrationResult<()> {
        let all_migrations = self.list_migrations_checked()?;
        let migration = all_migrations
            .iter()
            .find(|m| m.version == version)
            .ok_or_else(|| MigrationError::InvalidFilename {
                filename: version.to_string(),
            })?;

        let applied = self.get_applied_migrations(db).await?;
        if applied.contains(&migration.version) {
            return Ok(()); // Already applied
        }

        // Execute up SQL
        if !migration.up_sql.is_empty() {
            for stmt in migration.up_sql.split(';') {
                let stmt = stmt.trim();
                if stmt.is_empty() {
                    continue;
                }
                db.execute(stmt).await?;
            }
        }

        // Mark as applied
        self.mark_migration_applied(db, &migration.version).await?;

        Ok(())
    }

    /// Rollback a single migration by version
    pub async fn rollback_migration(
        &self,
        db: &impl crate::Database,
        version: &str,
    ) -> MigrationResult<()> {
        let all_migrations = self.list_migrations_checked()?;
        let migration = all_migrations
            .iter()
            .find(|m| m.version == version)
            .ok_or_else(|| MigrationError::InvalidFilename {
                filename: version.to_string(),
            })?;

        if migration.down_sql.is_empty() {
            return Err(MigrationError::InvalidFilename {
                filename: format!("migration {} has no down SQL", version),
            });
        }

        // Execute down SQL
        for stmt in migration.down_sql.split(';') {
            let stmt = stmt.trim();
            if stmt.is_empty() {
                continue;
            }
            db.execute(stmt).await?;
        }

        // Remove from tracking
        self.mark_migration_reverted(db, &migration.version).await?;

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::{Migration, MigrationManager};
    use crate::{sqlx, Database, DatabaseType, DbTransaction, Result, DbInspector, TableSchema};
    use async_trait::async_trait;
    use sqlx::any::AnyRow;
    use std::sync::Arc;
    use tokio::sync::Mutex;

    #[derive(Debug, Clone)]
    struct MockDb {
        db_type: DatabaseType,
        executed_sql: Arc<Mutex<Vec<String>>>,
    }

    impl MockDb {
        fn new(db_type: DatabaseType) -> Self {
            Self {
                db_type,
                executed_sql: Arc::new(Mutex::new(Vec::new())),
            }
        }

        async fn last_sql(&self) -> Option<String> {
            self.executed_sql.lock().await.last().cloned()
        }
    }

    #[async_trait]
    impl Database for MockDb {
        fn db_type(&self) -> DatabaseType {
            self.db_type
        }
        async fn execute(&self, query: &str) -> Result<u64> {
            self.executed_sql.lock().await.push(query.to_string());
            Ok(0)
        }
        async fn query(&self, _query: &str) -> Result<Vec<AnyRow>> {
            Ok(vec![])
        }
        async fn query_one(&self, _query: &str) -> Result<Option<AnyRow>> {
            Ok(None)
        }
        async fn ping(&self) -> Result<()> {
            Ok(())
        }
        async fn begin_transaction(&self) -> Result<DbTransaction> {
            unimplemented!()
        }
        async fn execute_query<'q>(
            &self,
            _query: sqlx::query::Query<'q, sqlx::Any, sqlx::any::AnyArguments<'q>>,
        ) -> Result<u64> {
            Ok(0)
        }
        async fn fetch_all<'q>(
            &self,
            _query: sqlx::query::Query<'q, sqlx::Any, sqlx::any::AnyArguments<'q>>,
        ) -> Result<Vec<AnyRow>> {
            Ok(vec![])
        }
        async fn fetch_one<'q>(
            &self,
            _query: sqlx::query::Query<'q, sqlx::Any, sqlx::any::AnyArguments<'q>>,
        ) -> Result<Option<AnyRow>> {
            Ok(None)
        }
        fn inspector(&self) -> Box<dyn DbInspector> {
            struct MockInspector;
            #[async_trait]
            impl DbInspector for MockInspector {
                async fn get_table_schema(&self, _table_name: &str) -> Result<Option<TableSchema>> {
                    Ok(None)
                }
                async fn list_tables(&self) -> Result<Vec<String>> {
                    Ok(vec![])
                }
            }
            Box::new(MockInspector)
        }
    }

    #[tokio::test]
    async fn ensure_migrations_table_uses_backend_specific_sql() {
        let manager = MigrationManager::new("migrations");

        let sqlite = MockDb::new(DatabaseType::Sqlite);
        manager.ensure_migrations_table(&sqlite).await.unwrap();
        assert!(sqlite.last_sql().await.unwrap().contains("AUTOINCREMENT"));

        let postgres = MockDb::new(DatabaseType::Postgres);
        manager.ensure_migrations_table(&postgres).await.unwrap();
        assert!(postgres.last_sql().await.unwrap().contains("BIGSERIAL"));

        let mysql = MockDb::new(DatabaseType::MySql);
        manager.ensure_migrations_table(&mysql).await.unwrap();
        assert!(mysql.last_sql().await.unwrap().contains("AUTO_INCREMENT"));
    }

    #[test]
    fn migration_from_file_checked_rejects_bad_filename() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("badname.sql");
        std::fs::write(
            &path,
            "-- migrate:up\nSELECT 1;\n-- migrate:down\nSELECT 1;",
        )
        .unwrap();

        let err = Migration::from_file_checked(&path).unwrap_err().to_string();
        assert!(err.contains("invalid migration filename"));
    }

    #[test]
    fn migration_from_file_parses_up_and_down_sql() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("20240101120000_create_users.sql");
        std::fs::write(
            &path,
            "-- migrate:up\nCREATE TABLE users (id INT);\n\n-- migrate:down\nDROP TABLE users;",
        )
        .unwrap();

        let migration = Migration::from_file_checked(&path).unwrap();
        assert!(migration.up_sql.contains("CREATE TABLE users"));
        assert!(migration.down_sql.contains("DROP TABLE users"));
        assert_eq!(migration.version, "20240101120000_create_users");
        assert_eq!(migration.name, "create_users");
    }

    #[test]
    fn migration_manager_lists_and_filters_pending() {
        let dir = tempfile::tempdir().unwrap();
        let migrations_dir = dir.path().join("migrations");
        std::fs::create_dir(&migrations_dir).unwrap();

        // Create two migration files
        std::fs::write(
            migrations_dir.join("20240101120000_create_users.sql"),
            "-- migrate:up\nCREATE TABLE users (id INT);\n-- migrate:down\nDROP TABLE users;",
        ).unwrap();
        std::fs::write(
            migrations_dir.join("20240102120000_create_posts.sql"),
            "-- migrate:up\nCREATE TABLE posts (id INT);\n-- migrate:down\nDROP TABLE posts;",
        ).unwrap();

        let manager = MigrationManager::new(&migrations_dir);
        let migrations = manager.list_migrations_checked().unwrap();
        assert_eq!(migrations.len(), 2);
        assert_eq!(migrations[0].name, "create_users");
        assert_eq!(migrations[1].name, "create_posts");
    }
}
